---
- name: Installation de Ngix dans serveur 1 et 2
  hosts: webserver
  become: true
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
    - name: copie de fichier html de test dans le serveur
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Hello World</title></head>
          <body>
          <h1>Page de test de Nginx!!!</h1>
          </body>
          </html>
    - name: Demarrage et activation de Ngix
      systemd:
        name: nginx 
        state: started
        enabled: true 